apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-simple
spec:
  subscriptions:
  - image:
      repoURL: docker.io/ssncvvarga/guestbook
      imageSelectionStrategy: SemVer
